# -*- coding: utf-8 -*-
"""Assignment2E1_Time_Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9OHyhKW4vj5rNv_yxNrnSxlnGBPmfBh
"""

# install pycaret
!pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
gold_data_fpath = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/gold_price_data.csv'

# read data
import pandas as pd
gold_data = pd.read_csv(gold_data_fpath)

# check data
gold_data.shape

# plot the dataset
gold_data.plot()

# review data stats
gold_data.describe

gold_data['Date']=pd.to_datetime(gold_data['Date'])
#gold_data.set_index('Date', inplace=True, drop=True)
gold_data.describe

# import pycaret time series and init setup
from pycaret.time_series import *
s = setup(gold_data, target='Value', session_id = 111)

# compare baseline models
best = compare_models()

# plot forecast
plot_model(best, plot = 'forecast')

plot_model(best, plot='ts')

plot_model(best, plot='cv')

plot_model(best, plot='diagnostics')

# save pipeline
save_model(best, 'my_TS_pipeline')