# -*- coding: utf-8 -*-
"""Assignment2A3_Gradio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jm0ZWjQK5ra4vf8dppyo7eEXyt2bdCMH
"""

# install pycaret
!pip install pycaret
# gradio app
!pip install gradio

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
crab_age_path = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/CrabAgePrediction.csv'

# read data
import pandas as pd
crab_age_regression = pd.read_csv(crab_age_path)

# check data
crab_age_regression.shape

# import pycaret regression and init setup
from pycaret.regression import *
reg = setup(crab_age_regression, target = 'Age', session_id = 333)

gbr_regressor = create_model('gbr')

print(gbr_regressor)



create_app(gbr_regressor)

save_model(gbr_regressor, "my_gradio1_model")