# -*- coding: utf-8 -*-
"""Assignment2A2_Multi_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3tXrlVBS3EQGt_9raZhVKweC0jTHmnb
"""

# install pycaret
!pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# import pycaret classification
from pycaret.classification import *

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
drug_path = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/drug_detaset.csv'

# read data
import pandas as pd
drug_class = pd.read_csv(drug_path)

# check data
drug_class.shape

drug_class.head()

# create train data
data_train = drug_class.sample(frac=0.9)
data_train.shape

data_train.head()

data_test = drug_class.drop(data_train.index)
data_test.shape

data_test.head()

data_train.reset_index(drop=True, inplace=True)
data_train.head()

data_test.reset_index(drop=True, inplace=True)
data_test.head()

s = setup(data_train, target = 'Drug')

# compare baseline models
best = compare_models()

# plot confusion matrix
plot_model(best, plot = 'confusion_matrix')

# plot AUC
plot_model(best, plot = 'auc')

# plot feature importance
plot_model(best, plot = 'feature')

rf_classifier = create_model('rf')

print(rf_classifier)

tuned_rf_classifier=tune_model(rf_classifier)

print(tuned_rf_classifier)

plot_model(tuned_rf_classifier, plot="class_report")

plot_model(tuned_rf_classifier, plot="error")

evaluate_model(tuned_rf_classifier)

# save pipeline
final_rf = finalize_model(tuned_rf_classifier)
print(final_rf)

test_prediction = predict_model(final_rf, data=data_test)
test_prediction.head()