# -*- coding: utf-8 -*-
"""Assignment2A3_Gradio2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMybxxdpAmJ__n7o6wOS0bBRR9OxjuPO
"""

# install pycaret
!pip install pycaret
# gradio app
!pip install gradio

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
car_data_fpath = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/used_car_price.csv'

# read data
import pandas as pd
car_data_regression = pd.read_csv(car_data_fpath)

# check data
car_data_regression.shape

# import pycaret regression and init setup
from pycaret.regression import *
reg = setup(car_data_regression, target = 'Present_Price', session_id = 333)

best = compare_models()

en_regressor = create_model('en')

create_app(en_regressor)

save_model(en_regressor, "my_gradio2_model")