# -*- coding: utf-8 -*-
"""Assignment2B_Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDKkCk5V_Xqjlc0KmIDTXlWSwSjmP9kL
"""

# install pycaret
!pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
customer_pers_fpath = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/customer_personality.csv'

# read data
import pandas as pd
customer_data = pd.read_csv(customer_pers_fpath)

# check data
customer_data.shape

customer_data.head()

customer_data.columns

customer_data.describe

# create train data
data_train = customer_data.sample(frac=0.9)
data_train.shape

data_train.head()

data_test = customer_data.drop(data_train.index)
data_test.shape

data_test.head()

data_train.reset_index(drop=True, inplace=True)
data_train.head()

data_test.reset_index(drop=True, inplace=True)
data_test.head()

# import pycaret clustering
from pycaret.clustering import *
clust = setup(data=data_train, normalize=True, ignore_features=["ID"])

kmeans = create_model('kmeans')

print(kmeans)

kmeans_result = assign_model(kmeans)
kmeans_result.head()

plot_model(kmeans)

plot_model(kmeans, plot="distribution")

# save pipeline
test_prediction = predict_model(kmeans, data=data_test)
test_prediction.head()

save_model(kmeans, "my_clustering_model")