# -*- coding: utf-8 -*-
"""Assignment2E2_Time_Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsLLSgLlDO3eim9uVttV9oEgbeWslUdd
"""

# install pycaret
!pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
digi_currancy_fpath = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/dc.csv'

# read data
import pandas as pd
dc_data = pd.read_csv(digi_currancy_fpath)

# check data
dc_data.shape

# plot the dataset
dc_data.plot()

# review data stats
dc_data.describe

dc_data['Date']=pd.to_datetime(dc_data['Date'])
dc_data = dc_data.drop(columns=['open_SAR', 'high_SAR','low_SAR','close_SAR'], axis=1)
dc_data.describe

# import pycaret time series and init setup
from pycaret.time_series import *
s = setup(dc_data, target='volume', session_id = 111)

# compare baseline models
best = compare_models()

# plot forecast
plot_model(best, plot = 'forecast')

plot_model(best, plot='ts')

plot_model(best, plot='cv')

plot_model(best, plot='diagnostics')

# save pipeline
save_model(best, 'my_TS2_pipeline')