# -*- coding: utf-8 -*-
"""Assignment2C_Anomaly_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCzpC0FJ07po0Fej64yaH4uNjkGnY0bI
"""

# install pycaret
!pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
land_mines_fpath = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/land_mines.csv'

# read data
import pandas as pd
lm_data = pd.read_csv(land_mines_fpath)

# check data
lm_data.shape

# review sample data
lm_data.head()

# review comlumns
lm_data.columns

# review data stats
lm_data.describe

# import pycaret clustering
from pycaret.anomaly import *
clust = setup(data=lm_data, normalize=True, ignore_features=["M"])

iforest = create_model("iforest")

print(iforest)

iforest_result = assign_model(iforest)
iforest_result.head()

plot_model(iforest)

save_model(iforest, "my_anomaly_test_model")