# -*- coding: utf-8 -*-
"""Assignment2E1_Time_Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9OHyhKW4vj5rNv_yxNrnSxlnGBPmfBh
"""

# install pycaret
!pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# loading the same dataset from pycaret dataset module
from pycaret.datasets import get_data
data = get_data('airline')

# plot the dataset
data.plot()

# review data stats
data.describe

# import pycaret time series and init setup
from pycaret.time_series import *
s = setup(data, fh = 3)

# check statistical tests on original data
check_stats()

# compare baseline models
best = compare_models()

# plot forecast
plot_model(best, plot = 'forecast')

# save pipeline
save_model(best, 'my_TS_pipeline')