# -*- coding: utf-8 -*-
"""Assignment2D_Association_Rule.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qUVxya_pDKc_II-xiWkAojLIrcuVh5Pm
"""

import sys
if sys.version_info[0] == 3:
    print('Python3')
else:
    print('Python2')
# Python3

# install pycaret
!pip install pycaret==3.0.0.rc1

# check installed version
import pycaret
pycaret.__version__

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
bakery_fpath = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/bakery.csv'

# read data
import pandas as pd
bakery_data = pd.read_csv(bakery_fpath)

# check data
bakery_data.shape

# review sample data
bakery_data.head()

# review comlumns
bakery_data.columns

# review data stats
bakery_data.describe

# import pycaret arules
from pycaret.arules import *
arule = setup(bakery_data, transaction_id='TransactionNo', item_id='Items')

rules = create_model()
rules.head()

plot_model(rules)