# -*- coding: utf-8 -*-
"""Assignment2A_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTgw8cUtNQyjHFAozvvIohZIkwqrl5DL
"""

# mount google drive
from google.colab import drive
drive.mount("/content/gdrive")
smk_path = '/content/gdrive/MyDrive/Sem-I/CMPE-255 Data Mining/Assignments2/smoking_dataset.csv'

# read data
import pandas as pd
smk_detection = pd.read_csv(smk_path)

# check data
smk_detection.head()

# check null values
smk_detection.isnull().sum()

pip install pycaret

# check installed version
import pycaret
pycaret.__version__

# import pycaret classification and init setup
from pycaret.classification import *
s = setup(smk_detection, target = 'smoking')

# compare baseline models
best = compare_models()

# plot confusion matrix
plot_model(best, plot = 'confusion_matrix')

# plot AUC
plot_model(best, plot = 'auc')

# plot feature importance
plot_model(best, plot = 'feature')

et_classifier = create_model('et')

tuned_et_classifier=tune_model(et_classifier)

# save pipeline
final_best = finalize_model(best)
save_model(best, 'my_first_classification_assignment')